apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog/nfd/operator/overlays/stable?ref=main

patches:
  - target:
      kind: Subscription
      name: nfd
    path: patch-channel.yaml
  # Rename OperatorGroup to match OSD/OpenShift naming convention
  - target:
      kind: OperatorGroup
      name: nfd-group
    patch: |-
      - op: replace
        path: /metadata/name
        value: openshift-nfd-og
