apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - github.com/redhat-cop/gitops-catalog/leader-worker-set/operator/overlays/stable-v1.0?ref=main

patches:
  # Rename OperatorGroup to match bu-nightly naming
  - target:
      kind: OperatorGroup
      name: openshift-lws-operator
    patch: |-
      - op: replace
        path: /metadata/name
        value: leader-worker-set
